### ISSUE TITLE
API to access the algorithms for the frontend.

### ISSUE THREAD

**Issue by CutieAlesia** [Kushurando/Software-Projekt-Management---Pathfinder#11]

**Comment by DubskySteam** [comment]
+ added Interfaces
+ added API layer
+ working transmission for Node Objects

**Comment by DubskySteam** [comment]
### [Reference PR](https://github.com/Kushurando/Software-Projekt-Management---Pathfinder/pull/26)
### [Reference Build](http://185.194.217.213:8111/buildConfiguration/SpmPathfinder_Build/23?buildTab=overview)
